"""Synthesize rationales for OPeRA-filtered actions via Gemini 2.5 Flash.

The Customer-R1 paper (arxiv 2510.07230) cites Lu et al. (2025a) for rationale
augmentation, where Claude-3.5-Sonnet generates a 1-2 sentence rationale per
(persona, current page HTML, executed action) tuple. The paper does not
publish the exact synthesis prompt; we reproduce it in
`prompts/rationale_synthesis.jinja`.

We swap Claude for **Gemini 2.5 Flash** (Google AI Studio free tier) to keep
on-device synthesis cost at zero. The trained model gets a slightly different
distribution of imitation targets than the paper, but the impact on SFT loss
shape is small — the rationale is short and constrained, and the difficulty-
aware GRPO reward depends only on the action, not the rationale text.

I/O:
  In:    data/trajectories/{train,test}.jsonl           (one row per session)
  Cache: data/trajectories_synth/.cache/rationales.jsonl (one row per (action_id,
         rationale); resume-safe, append-only)
  Out:   data/trajectories_synth/{train,test}.jsonl     (same shape as input,
         with step.rationale_synth populated for steps lacking rationale_gt)

The cache is the source of truth — the main output is regenerated by
materializing trajectories + cache. So if a run is interrupted, restart with
the same arguments and only the missing actions get re-requested.

Auth: GEMINI_API_KEY (loaded from .env via python-dotenv if available).

Rate limit: Google AI Studio free tier for Gemini 2.5 Flash is (as of writing)
~10 RPM / 250 RPD / 250k TPM. We default to 8 RPM throttle and back off on 429.
Long jobs may stretch over multiple days because of the daily cap.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import time
from pathlib import Path
from typing import Iterator, Optional


# --- environment / API key loading ----------------------------------------

def load_env(dotenv_path: Path) -> None:
    """Load .env into os.environ. Tries python-dotenv, falls back to manual parse."""
    if not dotenv_path.exists():
        return
    try:
        from dotenv import load_dotenv
        load_dotenv(dotenv_path)
        return
    except ImportError:
        pass
    for line in dotenv_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


# --- Gemini client --------------------------------------------------------

def get_client():
    from google import genai
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        sys.exit("GEMINI_API_KEY not set (check .env or environment)")
    return genai.Client(api_key=api_key)


def synthesize_one(
    client,
    template,
    persona_json: str,
    observation: str,
    action_wire_json: str,
    model: str = "gemini-2.5-flash",
    max_observation_chars: int = 80_000,
) -> str:
    """Generate a single 1-2 sentence rationale. Returns stripped text."""
    obs = observation
    if len(obs) > max_observation_chars:
        obs = obs[:max_observation_chars] + "\n<!-- observation truncated for synthesis context -->"

    prompt = template.render(
        persona_json=persona_json,
        observation=obs,
        action_wire=action_wire_json,
        few_shot_examples=[],  # hook for future use of the 164 human rationales
    )
    response = client.models.generate_content(
        model=model,
        contents=prompt,
    )
    text = (response.text or "").strip()
    # Strip surrounding quotes if the model added them despite our instructions.
    if (text.startswith('"') and text.endswith('"')) or (text.startswith("'") and text.endswith("'")):
        text = text[1:-1].strip()
    return text


# --- cache I/O ------------------------------------------------------------

def load_cache(cache_path: Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    if not cache_path.exists():
        return out
    with cache_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                r = json.loads(line)
            except json.JSONDecodeError:
                continue
            aid = r.get("action_id")
            if aid:
                out[aid] = r
    return out


def append_cache(cache_path: Path, entry: dict) -> None:
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    with cache_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


# --- iterate steps needing synthesis --------------------------------------

def iter_pending(
    traj_dir: Path, splits: list[str], cache: dict[str, dict]
) -> Iterator[tuple[str, dict, int]]:
    """Yield (split, session_dict, step_idx) for steps without human rationale
    and not yet in cache."""
    for split in splits:
        in_path = traj_dir / f"{split}.jsonl"
        if not in_path.exists():
            continue
        with in_path.open("r", encoding="utf-8") as f:
            for line in f:
                session = json.loads(line)
                for i, step in enumerate(session["steps"]):
                    if step.get("rationale_gt"):
                        continue
                    if step["action_id"] in cache:
                        continue
                    yield split, session, i


# --- materialize final JSONL ---------------------------------------------

def materialize_output(
    traj_dir: Path, out_dir: Path, cache: dict[str, dict], splits: list[str]
) -> dict:
    """Read trajectories/{split}.jsonl, fill step.rationale_synth from cache,
    write trajectories_synth/{split}.jsonl. Steps with human rationale_gt are
    untouched."""
    summary: dict = {}
    for split in splits:
        in_path = traj_dir / f"{split}.jsonl"
        out_path = out_dir / f"{split}.jsonl"
        out_dir.mkdir(parents=True, exist_ok=True)
        n_total = 0
        n_human = 0
        n_synth = 0
        n_none = 0
        with in_path.open("r", encoding="utf-8") as fin, out_path.open("w", encoding="utf-8") as fout:
            for line in fin:
                session = json.loads(line)
                for step in session["steps"]:
                    n_total += 1
                    if step.get("rationale_gt"):
                        n_human += 1
                        continue
                    entry = cache.get(step["action_id"])
                    if entry and entry.get("rationale"):
                        step["rationale_synth"] = entry["rationale"]
                        n_synth += 1
                    else:
                        n_none += 1
                fout.write(json.dumps(session, ensure_ascii=False) + "\n")
        summary[split] = {
            "out": str(out_path),
            "total_steps": n_total,
            "rationale_human": n_human,
            "rationale_synth_filled": n_synth,
            "rationale_missing": n_none,
        }
    return summary


# --- main loop ------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--traj_dir", type=Path, default=Path("data/trajectories"))
    ap.add_argument("--out_dir", type=Path, default=Path("data/trajectories_synth"))
    ap.add_argument("--system_prompt", type=Path, default=Path("prompts/rationale_synthesis.jinja"))
    ap.add_argument("--splits", nargs="+", default=["train", "test"])
    ap.add_argument("--model", type=str, default="gemini-2.5-flash")
    ap.add_argument(
        "--rpm",
        type=float,
        default=8.0,
        help="Requests per minute throttle. Free tier is ~10 RPM; we leave headroom.",
    )
    ap.add_argument(
        "--max_observation_chars",
        type=int,
        default=80_000,
        help="Truncate per-action HTML at this many chars (~20k tokens) before sending.",
    )
    ap.add_argument("--limit", type=int, default=None, help="Cap total new API calls (debug).")
    ap.add_argument("--dotenv", type=Path, default=Path(".env"))
    ap.add_argument(
        "--materialize_only",
        action="store_true",
        help="Skip API calls; just rebuild output JSONL from existing cache.",
    )
    ap.add_argument(
        "--max_retries",
        type=int,
        default=5,
        help="Retries per API call before giving up on a single action.",
    )
    args = ap.parse_args()

    load_env(args.dotenv)

    cache_path = args.out_dir / ".cache" / "rationales.jsonl"
    cache = load_cache(cache_path)
    print(f"[synth] cache: {len(cache)} existing entries at {cache_path}", flush=True)

    if args.materialize_only:
        summary = materialize_output(args.traj_dir, args.out_dir, cache, args.splits)
        print(json.dumps(summary, indent=2, ensure_ascii=False))
        return

    try:
        from jinja2 import Template
    except ImportError:
        sys.exit("pip install jinja2")

    template = Template(args.system_prompt.read_text(encoding="utf-8"))
    client = get_client()

    pending = list(iter_pending(args.traj_dir, args.splits, cache))
    print(f"[synth] {len(pending)} steps need synthesis", flush=True)
    if args.limit is not None:
        print(f"[synth] limit={args.limit} (will stop after that many new calls)", flush=True)

    interval = 60.0 / args.rpm if args.rpm > 0 else 0.0
    t_last = 0.0
    n_calls = 0
    n_errors = 0
    n_giveup = 0
    t_start = time.time()

    for split, session, step_idx in pending:
        if args.limit is not None and n_calls >= args.limit:
            break
        step = session["steps"][step_idx]
        action_id = step["action_id"]

        attempt = 0
        rationale: Optional[str] = None
        last_err: Optional[Exception] = None
        while attempt < args.max_retries:
            # Throttle only on the first attempt of each action.
            if attempt == 0:
                wait = interval - (time.time() - t_last)
                if wait > 0:
                    time.sleep(wait)
                t_last = time.time()
            try:
                rationale = synthesize_one(
                    client, template,
                    session["persona"], step["observation"], step["action_wire_json"],
                    model=args.model,
                    max_observation_chars=args.max_observation_chars,
                )
                if rationale:
                    break
                last_err = RuntimeError("empty response")
            except Exception as e:
                last_err = e
                msg = str(e).lower()
                if "429" in msg or "rate" in msg or "quota" in msg or "resource_exhausted" in msg:
                    backoff = 60.0 * (2 ** attempt) + random.uniform(0, 5)
                else:
                    backoff = 5.0 * (2 ** attempt) + random.uniform(0, 2)
                print(
                    f"  [retry {attempt+1}/{args.max_retries}] {type(e).__name__}: "
                    f"{str(e)[:120]}  sleeping {backoff:.0f}s",
                    flush=True,
                )
                time.sleep(backoff)
            attempt += 1

        if not rationale:
            n_giveup += 1
            n_errors += 1
            print(f"  [gave up] action_id={action_id} after {args.max_retries} attempts: {last_err}", flush=True)
            continue

        entry = {
            "action_id": action_id,
            "session_id": session["session_id"],
            "step_idx": int(step_idx),
            "split": split,
            "model": args.model,
            "rationale": rationale,
        }
        append_cache(cache_path, entry)
        cache[action_id] = entry
        n_calls += 1

        if n_calls % 25 == 0:
            elapsed = time.time() - t_start
            rpm_eff = n_calls / (elapsed / 60.0) if elapsed > 0 else 0.0
            print(
                f"  [{split}] synthesized {n_calls} new (cache total {len(cache)}, "
                f"errors {n_errors}, eff {rpm_eff:.1f} RPM)",
                flush=True,
            )

    print(
        f"[synth] done. {n_calls} new, {n_errors} errors, {n_giveup} gave up. "
        f"cache total: {len(cache)}",
        flush=True,
    )

    summary = materialize_output(args.traj_dir, args.out_dir, cache, args.splits)
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
